package com.superdl.launcher.currency

import android.content.Context
import android.graphics.Bitmap
import android.graphics.RectF
import java.io.Closeable

/**
 * Two-stage HUF banknote recognition engine for Super DL.
 *
 * **Assets** (generated by `tools/train_banknote_full_pipeline.py`):
 * - `huf_banknote_detector.tflite` + `huf_banknote_detector_labels.txt`  → Stage 1 (YOLO)
 * - `huf_banknote_classifier.tflite` + `huf_banknote_labels.txt`            → Stage 2 (MobileNet)
 *
 * **Pipeline per camera frame:**
 * ```
 * Bitmap → [Stage 1: YOLO detect] → crop bbox (+6% pad) → [Stage 2: classify] → result
 *            ↓ no box / no detector
 *          center-ROI → classify → full-frame classify (fallback chain)
 * ```
 *
 * Stage 1 and Stage 2 must agree on denomination when both are highly confident;
 * otherwise the engine abstains (`null`) rather than risk a wrong announcement.
 */
class BanknoteClassifierEngine private constructor(
    private val detector: BanknoteYoloDetector?,
    private val classifier: BanknoteDenominationClassifier
) : Closeable {

    private var cachedDetection: BanknoteDetection? = null
    private var cachedDetectionAtMs: Long = 0L
    private var frameCounter: Int = 0

    /** `true` when `huf_banknote_detector.tflite` is present in assets. */
    val isTwoStageEnabled: Boolean
        get() = detector != null

    /**
     * Process one camera frame. Safe to call from a background thread.
     * Returns `null` when uncertain — callers should not speak a denomination.
     */
    fun classify(bitmap: Bitmap): BanknoteClassificationResult? =
        processFrame(bitmap, applyColorCheck = true)

    /** Volume-button / manual verification — slightly relaxed color gate. */
    fun classifyForManualCheck(bitmap: Bitmap): BanknoteClassificationResult? =
        processFrame(bitmap, applyColorCheck = true)

    private fun processFrame(bitmap: Bitmap, applyColorCheck: Boolean): BanknoteClassificationResult? {
        if (bitmap.isRecycled || bitmap.width <= 0 || bitmap.height <= 0) return null

        // ── Stage 1 + 2: detect → crop → classify ──────────────────────────
        runTwoStage(bitmap, applyColorCheck)?.let { return it }

        // ── Fallback: center ROI (simulates user holding bill in frame) ───
        BanknoteBitmapCropper.centerRoi(bitmap)?.let { roi ->
            try {
                classifier.classify(roi, applyColorCheck)?.let { result ->
                    return result.copy(
                        pipelineMode = BanknotePipelineMode.ROI_FALLBACK,
                        detectionBox = null,
                        detectionConfidence = 0f
                    )
                }
            } finally {
                if (roi !== bitmap) roi.recycle()
            }
        }

        // ── Fallback: full frame ───────────────────────────────────────────
        return classifier.classify(bitmap, applyColorCheck)?.copy(
            pipelineMode = BanknotePipelineMode.FULL_FRAME_FALLBACK,
            detectionBox = null,
            detectionConfidence = 0f
        )
    }

    private fun runTwoStage(bitmap: Bitmap, applyColorCheck: Boolean): BanknoteClassificationResult? {
        val stage1 = detector ?: return null
        val detection = resolveDetection(stage1, bitmap) ?: return null

        val crop = BanknoteBitmapCropper.crop(bitmap, detection) ?: return null
        return try {
            val stage2 = classifier.classify(crop, applyColorCheck) ?: return null
            reconcileStages(detection, stage2)
        } finally {
            if (crop !== bitmap) crop.recycle()
        }
    }

    /**
     * Cross-check YOLO class vs classifier. Mismatch at high confidence → abstain.
     */
    private fun reconcileStages(
        detection: BanknoteDetection,
        classification: BanknoteClassificationResult
    ): BanknoteClassificationResult? {
        val yoloDenomination = detection.denomination
        if (yoloDenomination != null && yoloDenomination != classification.denomination) {
            val yoloStrong = detection.confidence >= STAGE_AGREE_MIN_CONF
            val clsStrong = classification.confidence >= STAGE_AGREE_MIN_CONF
            if (yoloStrong && clsStrong) return null
        }

        return classification.copy(
            detectionConfidence = detection.confidence,
            pipelineMode = BanknotePipelineMode.TWO_STAGE,
            detectionBox = RectF(detection.boundingBox)
        )
    }

    /** Cash Reader–style speed: YOLO every 2nd frame; reuse bbox ~450 ms. */
    private fun resolveDetection(stage1: BanknoteYoloDetector, bitmap: Bitmap): BanknoteDetection? {
        frameCounter++
        val now = System.currentTimeMillis()
        val cacheFresh = cachedDetection != null && now - cachedDetectionAtMs <= DETECTION_CACHE_MS
        if (cacheFresh && frameCounter % DETECTOR_EVERY_N_FRAMES != 0) {
            return cachedDetection
        }
        val fresh = stage1.bestDetection(bitmap)
        if (fresh != null) {
            cachedDetection = fresh
            cachedDetectionAtMs = now
        }
        return fresh ?: cachedDetection
    }

    override fun close() {
        cachedDetection = null
        detector?.close()
        classifier.close()
    }

    companion object {
        private const val STAGE_AGREE_MIN_CONF = 0.62f
        private const val DETECTOR_EVERY_N_FRAMES = 2
        private const val DETECTION_CACHE_MS = 450L

        /**
         * Load both TFLite models from assets.
         * @throws IllegalStateException if the classifier model/labels are missing
         */
        fun create(context: Context): BanknoteClassifierEngine {
            val appContext = context.applicationContext
            val classifier = BanknoteDenominationClassifier.create(appContext)
            val detector = BanknoteYoloDetector.tryCreate(appContext)
            return BanknoteClassifierEngine(detector, classifier)
        }
    }
}